# SonarQube Cloud Project Identification
sonar.projectKey=YOUR_PROJECT_KEY
sonar.organization=YOUR_ORGANIZATION_KEY

# Source folders
sonar.sources=lib,app

# Exclusions
sonar.exclusions=**/*.g.dart,**/vendor/**,**/node_modules/**
