# SonarQube Cloud Project Identification
sonar.projectKey=rubyones_php-sonarqube-project
sonar.organization=rubyones

# Source folders
sonar.sources=lib,app

# Ignore generated files
sonar.exclusions=**/*.g.dart,**/vendor/**,**/node_modules/**
